### ISSUE TITLE
SNOW-1727131: bump `packaging` to v24

### ISSUE THREAD

**Issue by josescuderoh** [snowflakedb/snowflake-ml-python#119]
Any chance [this dependency](https://github.com/snowflakedb/snowflake-ml-python/blob/6186ce6e52db9b85458e715572b71e29cb47371f/requirements.yml#L165) can be upgraded to the next major version soon?

It's available since March 10th and it's presenting dependency conflicts with other dependencies for us. For context, this is the conflict:

```
Because meltano (3.5.4) depends on packaging (>=24.1,<25.0)
 and snowflake-ml-python (1.6.2) depends on packaging (>=20.9,<24), meltano (3.5.4) is incompatible with snowflake-ml-python (1.6.2).
So, because project depends on both meltano (3.5.4) and snowflake-ml-python (1.6.2), version solving failed.
```

**Comment by lyleharte** [comment]
bump

**Comment by sfc-gh-zzhu** [comment]
We have relaxed the version requirement of Packaging to allow v24. The change will go out with release 1.7.1 soon.

**Comment by sfc-gh-afero** [comment]
this has been added in version 1.7.1
