### ISSUE TITLE
fsspec pinned to an aging version

### ISSUE THREAD

**Issue by ArtnerC** [snowflakedb/snowflake-ml-python#37]
Currently we are evaluating `snowflake-ml-python` for it's role in our migration so we need it installed on our Astronomer Deployment. We are also using `fsspec` for file moving/loading and are running into issues that have been fixed by newer versions of `fsspec`. For package management we are using Poetry which doesn't mess around when it comes to version conflicts (good). Since `snowpark-ml-python` pins `fsspec` to `2022.11,<=2023.1`, we can't install new versions of the package without removing the ml package.

Can the version pinning be removed or at least advanced?

Thanks!

**Comment by sfc-gh-zzhu** [comment]
Hi, we have made the code change to relax the version constraint of fsspec. The new version requirement will become `>=2022.11,<2024`. The change will be released with snowflake-ml-python-1.0.7.

**Comment by ArtnerC** [comment]
Awesome, thank you!

**Comment by sfc-gh-wzhao** [comment]
Fix has been implemented and released. Closing this issue.
