### ISSUE TITLE
SNOW-991679: Support pandas 2.0

### ISSUE THREAD

**Issue by kylejcaron** [snowflakedb/snowflake-ml-python#77]
The current version limits pandas to be <2.0, making it incompatible with some projects Im working on

**Comment by sfc-gh-wzhao** [comment]
Hi kylejcaron,

We are still working on adapting and testing with pandas 2.x and we will make them compatible soon.

**Comment by sfc-gh-pdorairaj** [comment]
Hi kylejcaron,

This will be supported in the next release. Code is already merged.
